# coding: utf-8

"""
    Site Reliable Engineer Test

    SRE Test - Loadsmart  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jobs@loadsmart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.machine_id import MachineId  # noqa: E501
from swagger_client.rest import ApiException


class TestMachineId(unittest.TestCase):
    """MachineId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMachineId(self):
        """Test MachineId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.machine_id.MachineId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
