# coding: utf-8

"""
    Site Reliable Engineer Test

    SRE Test - Loadsmart  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jobs@loadsmart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attach_instance(self):
        """Test case for attach_instance

        """
        pass

    def test_elb_elb_name_delete(self):
        """Test case for elb_elb_name_delete

        """
        pass

    def test_healthcheck_get(self):
        """Test case for healthcheck_get

        """
        pass

    def test_list_machines_elb(self):
        """Test case for list_machines_elb

        """
        pass


if __name__ == '__main__':
    unittest.main()
