# coding: utf-8

"""
    Site Reliable Engineer Test

    SRE Test - Loadsmart  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: jobs@loadsmart.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class MachineInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance_id': 'str',
        'instance_type': 'str',
        'launch_date': 'str'
    }

    attribute_map = {
        'instance_id': 'instanceId',
        'instance_type': 'instanceType',
        'launch_date': 'launchDate'
    }

    def __init__(self, instance_id=None, instance_type=None, launch_date=None, _configuration=None):  # noqa: E501
        """MachineInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._instance_id = None
        self._instance_type = None
        self._launch_date = None
        self.discriminator = None

        self.instance_id = instance_id
        self.instance_type = instance_type
        self.launch_date = launch_date

    @property
    def instance_id(self):
        """Gets the instance_id of this MachineInfo.  # noqa: E501


        :return: The instance_id of this MachineInfo.  # noqa: E501
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this MachineInfo.


        :param instance_id: The instance_id of this MachineInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instance_id is None:
            raise ValueError("Invalid value for `instance_id`, must not be `None`")  # noqa: E501

        self._instance_id = instance_id

    @property
    def instance_type(self):
        """Gets the instance_type of this MachineInfo.  # noqa: E501


        :return: The instance_type of this MachineInfo.  # noqa: E501
        :rtype: str
        """
        return self._instance_type

    @instance_type.setter
    def instance_type(self, instance_type):
        """Sets the instance_type of this MachineInfo.


        :param instance_type: The instance_type of this MachineInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instance_type is None:
            raise ValueError("Invalid value for `instance_type`, must not be `None`")  # noqa: E501

        self._instance_type = instance_type

    @property
    def launch_date(self):
        """Gets the launch_date of this MachineInfo.  # noqa: E501


        :return: The launch_date of this MachineInfo.  # noqa: E501
        :rtype: str
        """
        return self._launch_date

    @launch_date.setter
    def launch_date(self, launch_date):
        """Sets the launch_date of this MachineInfo.


        :param launch_date: The launch_date of this MachineInfo.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and launch_date is None:
            raise ValueError("Invalid value for `launch_date`, must not be `None`")  # noqa: E501

        self._launch_date = launch_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MachineInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MachineInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MachineInfo):
            return True

        return self.to_dict() != other.to_dict()
